USE checkers;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
	user_id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	login VARCHAR(32) NOT NULL,
	password CHAR(32) NOT NULL,
	name VARCHAR(32) NOT NULL,
	PRIMARY KEY(user_id)
);

CREATE TABLE games(
	game_id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	player1_id INT(8) UNSIGNED NOT NULL,
	player2_id INT(8) UNSIGNED NOT NULL,
	date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(game_id),
	FOREIGN KEY(player1_id)
		REFERENCES users(user_id),
	FOREIGN KEY(player2_id)
		REFERENCES users(user_id)
);